# Minimal CI - Build Check Only
# AIDEV-NOTE: simplified-ci; KISS principle - only verify if code builds

name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

  build-termux:
    name: Build Termux/Android
    runs-on: ubuntu-latest
    container:
      image: termux/termux-docker:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pkg update -y
          pkg install -y nodejs-lts
          npm ci
          npm run build